server:
  port: ${SERVER_PORT:8084}
  shutdown: graceful #Wait if it has any action
  forward-headers-strategy: framework
spring:
  application:
    name: application
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/application_db1}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      max-lifetime: ${DB_MAX_LIFETIME:30000}
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:50}
      pool-name: Hikari
  lifecycle:
    timeout-per-shutdown-phase: 30s #After determination waiting for 30 seconds
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /v1/application/index.html
  api-docs:
    path: /v1/application/api-docs